backend:
  name: git-gateway
  branch: main
  media_folder: "images/uploads"
  collections:
    - label: "gatsby site"
      name: "gatsby site"
      files:
        - label: "landing page"
          name: "landing page"
          file: ""
      fields:
        repo: "Evan2260/gatsby-site"
